const hotLeads = [
  "08/05/2024",
  "Admin" "Created",
  "Agent Created",
  "Alba Cars",
  "AlwData",
  "Ask a Question",
  "Bayut",
  "Bilal",
  "Call Center",
  "Call Center 1",
  "Call Center 2",
  "Call Center 2",
  "Call Center 3",
  "Call Center 4",
  "Dubizzle",
  "Dubizzle Listing",
  "Email",
  "Facebook Call",
  "Facebook Campaign",
  "Facebook Chat",
  "Get Matched Assistance",
  "Google Ads",
  "Hot Confidential",
  "Instagram",
  "Instagram Call",
  "Instagram Campaign",
  "Instagram Chat",
  "LinkedIn",
  "Meta",
  "New Listing",
  "Newsletter",
  "Off-Plan",
  "Property Finder",
  "Referral",
  "Register",
  "Rent",
  "Research",
  "Saqib",
  "Snapchat",
  "Taboola",
  "TikTok",
  "Twitter",
  "Unkown Inbound Call",
  "Viewing",
  "Watti",
  "Whatsapp",
  "dina@alba.homes",
  "facebook",
  "ibrahim@alba.homes",
  "jay@alba.homes",
  "m.naeem@alba.homes",
  "susan@alba.homes",
  "touseef@alba.homes",
  "waqas@alba.homes"
];
