// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_oi6oScWnZksXUAa3_efkGXVDDXTug4',
    appId: '1:496432202958:android:188bdc214daf3c6802fc9f',
    messagingSenderId: '496432202958',
    projectId: 'agent-app-2cc24',
    storageBucket: 'agent-app-2cc24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDre7ULnGWrhPvx5D3AL4L7J1K1MN69JnU',
    appId: '1:496432202958:ios:73f99163e691c05302fc9f',
    messagingSenderId: '496432202958',
    projectId: 'agent-app-2cc24',
    storageBucket: 'agent-app-2cc24.appspot.com',
    iosBundleId: 'com.alba.agent-app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-pF6M09Wi7GjG3RBS8fn8y-zb8DZRGk',
    appId: '1:496432202958:web:70dbc94333f7608002fc9f',
    messagingSenderId: '496432202958',
    projectId: 'agent-app-2cc24',
    authDomain: 'agent-app-2cc24.firebaseapp.com',
    storageBucket: 'agent-app-2cc24.appspot.com',
    measurementId: 'G-604XPCBHVZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDre7ULnGWrhPvx5D3AL4L7J1K1MN69JnU',
    appId: '1:496432202958:ios:f42423229449b0f602fc9f',
    messagingSenderId: '496432202958',
    projectId: 'agent-app-2cc24',
    storageBucket: 'agent-app-2cc24.appspot.com',
    iosBundleId: 'com.alba.agent-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD-pF6M09Wi7GjG3RBS8fn8y-zb8DZRGk',
    appId: '1:496432202958:web:6918c7462b1e4a1102fc9f',
    messagingSenderId: '496432202958',
    projectId: 'agent-app-2cc24',
    authDomain: 'agent-app-2cc24.firebaseapp.com',
    storageBucket: 'agent-app-2cc24.appspot.com',
    measurementId: 'G-4RQKLKWNEL',
  );
}