// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/objectbox/entity/notification_entity.dart';
import 'data/objectbox/entity/pending_call_feedback.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5795122159064061020),
      name: 'NotificationEntity',
      lastPropertyId: const obx_int.IdUid(6, 3017629158783680701),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2957280728844294631),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 81941689401433012),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8984158101847328840),
            name: 'subTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5946653610197968049),
            name: 'isRead',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3668146916538278613),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3017629158783680701),
            name: 'notificationId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7049694244653760523),
      name: 'PendingCallFeedbackEntity',
      lastPropertyId: const obx_int.IdUid(5, 8161508637393570831),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9826608743018263),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4820043944492960187),
            name: 'number',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1362298140004410048),
            name: 'feedback',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2873496119375944348),
            name: 'isSynced',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8161508637393570831),
            name: 'callDirection',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 7049694244653760523),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [6363046916056047050],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        1979810741703805588,
        272374996687882852,
        4471211523630168431,
        4717547009146856455,
        6538964272779489073
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    NotificationEntity: obx_int.EntityDefinition<NotificationEntity>(
        model: _entities[0],
        toOneRelations: (NotificationEntity object) => [],
        toManyRelations: (NotificationEntity object) => {},
        getId: (NotificationEntity object) => object.id,
        setId: (NotificationEntity object, int id) {
          object.id = id;
        },
        objectToFB: (NotificationEntity object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final subTitleOffset = object.subTitle == null
              ? null
              : fbb.writeString(object.subTitle!);
          final notificationIdOffset = object.notificationId == null
              ? null
              : fbb.writeString(object.notificationId!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, subTitleOffset);
          fbb.addBool(3, object.isRead);
          fbb.addInt64(4, object.createdAt?.millisecondsSinceEpoch);
          fbb.addOffset(5, notificationIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final notificationIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final subTitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final isReadParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final object = NotificationEntity(
              id: idParam,
              notificationId: notificationIdParam,
              title: titleParam,
              subTitle: subTitleParam,
              isRead: isReadParam,
              createdAt: createdAtParam);

          return object;
        }),
    PendingCallFeedbackEntity:
        obx_int.EntityDefinition<PendingCallFeedbackEntity>(
            model: _entities[1],
            toOneRelations: (PendingCallFeedbackEntity object) => [],
            toManyRelations: (PendingCallFeedbackEntity object) => {},
            getId: (PendingCallFeedbackEntity object) => object.id,
            setId: (PendingCallFeedbackEntity object, int id) {
              object.id = id;
            },
            objectToFB: (PendingCallFeedbackEntity object, fb.Builder fbb) {
              final numberOffset = fbb.writeString(object.number);
              final feedbackOffset = object.feedback == null
                  ? null
                  : fbb.writeString(object.feedback!);
              fbb.startTable(6);
              fbb.addInt64(0, object.id);
              fbb.addOffset(1, numberOffset);
              fbb.addOffset(2, feedbackOffset);
              fbb.addBool(3, object.isSynced);
              fbb.addInt64(4, object.callDirection);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final idParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
              final numberParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
              final callDirectionParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
              final feedbackParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 8);
              final isSyncedParam = const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 10, false);
              final object = PendingCallFeedbackEntity(
                  id: idParam,
                  number: numberParam,
                  callDirection: callDirectionParam,
                  feedback: feedbackParam,
                  isSynced: isSyncedParam);

              return object;
            })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NotificationEntity] entity fields to define ObjectBox queries.
class NotificationEntity_ {
  /// See [NotificationEntity.id].
  static final id =
      obx.QueryIntegerProperty<NotificationEntity>(_entities[0].properties[0]);

  /// See [NotificationEntity.title].
  static final title =
      obx.QueryStringProperty<NotificationEntity>(_entities[0].properties[1]);

  /// See [NotificationEntity.subTitle].
  static final subTitle =
      obx.QueryStringProperty<NotificationEntity>(_entities[0].properties[2]);

  /// See [NotificationEntity.isRead].
  static final isRead =
      obx.QueryBooleanProperty<NotificationEntity>(_entities[0].properties[3]);

  /// See [NotificationEntity.createdAt].
  static final createdAt =
      obx.QueryDateProperty<NotificationEntity>(_entities[0].properties[4]);

  /// See [NotificationEntity.notificationId].
  static final notificationId =
      obx.QueryStringProperty<NotificationEntity>(_entities[0].properties[5]);
}

/// [PendingCallFeedbackEntity] entity fields to define ObjectBox queries.
class PendingCallFeedbackEntity_ {
  /// See [PendingCallFeedbackEntity.id].
  static final id = obx.QueryIntegerProperty<PendingCallFeedbackEntity>(
      _entities[1].properties[0]);

  /// See [PendingCallFeedbackEntity.number].
  static final number = obx.QueryStringProperty<PendingCallFeedbackEntity>(
      _entities[1].properties[1]);

  /// See [PendingCallFeedbackEntity.feedback].
  static final feedback = obx.QueryStringProperty<PendingCallFeedbackEntity>(
      _entities[1].properties[2]);

  /// See [PendingCallFeedbackEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<PendingCallFeedbackEntity>(
      _entities[1].properties[3]);

  /// See [PendingCallFeedbackEntity.callDirection].
  static final callDirection =
      obx.QueryIntegerProperty<PendingCallFeedbackEntity>(
          _entities[1].properties[4]);
}
